---
title: "Combining Similarity and Eigenvector Analysis"
execute: 
  eval: true
  echo: true
  output: true
  warning: false
  message: false
format: 
   html:
      code-line-numbers: true
---

## Setup

```{r}
    library(networkdata)
    library(igraph)
    library(here)
    library(dplyr)
    library(tidyr)
    library(ggplot2)
    library(ggbump)
    library(ggrepel)
    g <- flo_marriage + flo_business
    g <- subgraph(g, which(degree(g) > 1))
```

## Network Plot

```{r}
    set.seed(345)
    png("medici.png", width = 800, height = 600)
    plot(g, 
        vertex.size=8, vertex.frame.color="lightgray", 
        vertex.label.dist=2, edge.curved=0.2, 
        vertex.label.cex = 1.2, edge.color = "gray",
        edge.width = 2)
    dev.off()
```

## Main Function

```{r}
    prestige.sim <- function(x, alpha = 0, beta = 0) {
        A <- as.matrix(as_adjacency_matrix(x))
        A.p <- A %*% A 
        A.q <- A %*% (1 - A)  
        S <- A.p / (A.p + A.q + t(A.q))
        D <- 1 - S
        W <- A * (S^alpha * D^beta)
        s <- abs(eigen(W)$vectors[, 1])
        names(s) <- rownames(A)
        s <- (s - min(s))/(max(s) - min(s))
        #s <- s/max(s)
        return(list(s = s, D = D, S = S, W = W))
        }
```

## Main Table

```{r}
    bon <- prestige.sim(g, alpha = 0, beta = 0)
    ace <- prestige.sim(g, alpha = 0, beta = 1)
    ol1 <- prestige.sim(g, alpha = 1, beta = 0)
    ol2 <- prestige.sim(g, alpha = 0.15, beta = 0.85)
    sort.vec <- function(x) {
        x <- data.frame(Node = names(x), Score = as.numeric(x))
        x <- x[order(x$Score, decreasing = TRUE), ]
        return(x)
        }
    eig.dat <- data.frame(sort.vec(bon$s), sort.vec(ace$s), sort.vec(ol1$s), sort.vec(ol2$s))
    library(kableExtra)
    library(here)
    kbl(eig.dat,
        format = "html",
        row.names = FALSE, align = rep(c("l", "c"), 4),
        digits = 3, col.names = c("Node", "Eig.", "Node", "Eig./Dis", "Node", "Eig./Sim", "Node", "Eig./Both"),
        caption = "Eigenvector-Based Scores for the Medici Network.", label = "tab:main") %>%    
        kable_styling(bootstrap_options = 
                    c("hover", "condensed", "responsive"))
```

```{r}
    save_kable(
        kbl(eig.dat,
            format = "latex", booktabs = TRUE, linesep = "",
            row.names = FALSE, align = rep(c("l", "c"), 4),
            digits = 3, col.names = c("Node", "Eig.", "Node", "Eig./Dis", "Node", "Eig./Sim", "Node", "Eig./Hybrid"),
            caption = "Eigenvector-Based Scores for the Medici Network.", label = "main") %>%    
            kable_styling(latex_options = c("scale_down")),
        file = here("main.tex")
        )
```

## Parameter Range Sensitivity Analysis

```{r}
    beta.range <- seq(0, 1, by = 0.05)
     for (b in beta.range) {
        a <- 1-b
         if (b == min(beta.range)) {
             c <- prestige.sim(g, alpha = a, beta = b)$s
             }
         else if (b > min(beta.range)) {
             c <- cbind(c, prestige.sim(g, alpha = a, beta = b)$s)
         }
     }
```

```{r}
    c.rank <- apply(c, 2, function(x){rank(x)})
    c.dat <- data.frame(c)
    names(c.dat) <- paste("V", 1:ncol(c), sep = "_")
    c.dat <- data.frame(person = cbind(rownames(c), c.dat))
    c.long <-  c.dat %>% 
         pivot_longer(
               cols = 1:ncol(c)+1,
               names_to = "Beta",
               values_to = "b"
          ) |> 
        rename(person = person.rownames.c.) |> 
        mutate(Beta = factor(Beta, ordered = TRUE, levels = colnames(c.dat)[-1])) 
    head(c.long)
```


```{r}
    p <- ggplot(data = c.long, mapping = aes(x = Beta, y = b, 
    color = person, group = person))
    p <- p + geom_vline(aes(xintercept = which(sprintf("%.2f", seq(0, 1, by = 0.05)) == "0.85")), linetype = 2, color = "red")
    p <- p + geom_bump(linewidth = 0.8, smooth = 2)
    p <- p + geom_point(size = 3)
    p <- p + geom_text_repel(
                            data = filter(c.long, 
                            Beta == colnames(c.dat)[2]),
                            aes(x = Beta, label = person), 
                            size = 6, nudge_x = -2.5
                            )
    p <- p + geom_text_repel(
                            data = filter(c.long, 
                            Beta == colnames(c.dat)[ncol(c.dat)]),
                            aes(x = Beta, label = person), 
                            size = 6, nudge_x = 2.5
                            )
    p <- p + theme_minimal()
    p <- p + labs(x = "")
    p <- p + theme(legend.position = "none",
        panel.grid.major = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        )
    p <- p + scale_x_discrete(
        breaks =  unique(c.long$Beta)[seq(1, 21, by = 2)],
        labels = sprintf("%.2f", seq(0, 1, by = 0.05))[seq(1, 21, by = 2)]
        )
    p <- p + theme(text = element_text(size = 24)) + xlab("Beta Value")
    p
    ggsave(here("bump.png"), height = 10, width = 15)
```